check if KUBECTL_PLUGIN_KA_HOST is set

diff --git a/kubectl-ka-pr-logs b/kubectl-ka-pr-logs
--- a/kubectl-ka-pr-logs
+++ b/kubectl-ka-pr-logs
@@ -7,6 +7,11 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+if [ -z "$KUBECTL_PLUGIN_KA_HOST" ]; then
+    echo "$0: Error: You must set KUBECTL_PLUGIN_KA_HOST to the Kubearchive address" >&2
+    exit 1
+fi
+
 if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
     if command -v kubectl > /dev/null; then
         KUBEARCHIVE_PR_LOGS_KUBECTL=kubectl
