search for installed Kubernetes client, allow override

diff --git a/kubectl-ka-pod-logs b/kubectl-ka-pod-logs
--- a/kubectl-ka-pod-logs
+++ b/kubectl-ka-pod-logs
@@ -7,25 +7,39 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-response=$(oc ka get pods "$1" --archived -o json)
+if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
+    if command -v kubectl > /dev/null; then
+        KUBEARCHIVE_PR_LOGS_KUBECTL=kubectl
+    fi
+    if command -v oc > /dev/null; then
+        KUBEARCHIVE_PR_LOGS_KUBECTL=oc
+    fi
+fi
+
+if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
+    echo "$0: Error: No Kubernetes client found" >&2
+    exit 1
+fi
+
+response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods "$1" --archived -o json)
 i=0
 while ( $(printf "%s" "$response" | grep -e '^pods.metrics.k8s.io' | grep -q -e 'cannot get resource "pods" in API group "metrics.k8s.io"') || [ "$response" = "KubeArchive authentication required: unauthorized" ] ) && [ "$i" -lt 10 ]; do
     if [ "$i" -gt 0 ]; then
         echo "Got unauthorized, retrying (${i} of 10)" >&2
     fi
-    response=$(oc ka get pods "$1" --archived -o json)
+    response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods "$1" --archived -o json)
     i=$((i+1))
 done
 
 for container in $(printf "%s" "$response" | jq -r ".items[].spec.containers[].name"); do
     printf "%s\n" "$container" | tr "[[:lower:]]" "[[:upper:]]"
-    response=$(oc ka logs "$1" -c "$container")
+    response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka logs "$1" -c "$container")
     i=0
     while [ "$response" = "unauthorized" ] && [ "$i" -lt 10 ]; do
         if [ "$i" -gt 0 ]; then
             echo "Got unauthorized, retrying (${i} of 10)" >&2
         fi
-        response=$(oc ka logs "$1" -c "$container")
+        response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka logs "$1" -c "$container")
         i=$((i+1))
     done
     printf "%s\n" "$response" | sed -e "s/^/  /"
diff --git a/kubectl-ka-pr-logs b/kubectl-ka-pr-logs
--- a/kubectl-ka-pr-logs
+++ b/kubectl-ka-pr-logs
@@ -7,13 +7,27 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-response=$(oc ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
+if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
+    if command -v kubectl > /dev/null; then
+        KUBEARCHIVE_PR_LOGS_KUBECTL=kubectl
+    fi
+    if command -v oc > /dev/null; then
+        KUBEARCHIVE_PR_LOGS_KUBECTL=oc
+    fi
+fi
+
+if [ -z "$KUBEARCHIVE_PR_LOGS_KUBECTL" ]; then
+    echo "$0: Error: No Kubernetes client found" >&2
+    exit 1
+fi
+
+response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
 i=0
 while [ "$response" = "KubeArchive authentication required: unauthorized" ] && [ "$i" -lt 10 ]; do
     if [ "$i" -gt 0 ]; then
         echo "Got unauthorized, retrying (${i} of 10)" >&2
     fi
-    response=$(oc ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
+    response=$("$KUBEARCHIVE_PR_LOGS_KUBECTL" ka get pods -l tekton.dev/pipelineRun="$1" --archived -o json)
     i=$((i+1))
 done
 
